name: application_pco_sense
description: A new Flutter project.

publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"  # Ensure it's under 'environment'

# dependencies:
  #flutter:
  #sdk: flutter
  #http: ^1.3.0
  #provider: ^6.0.0
  #cupertino_icons: ^1.0.8
  #change(23-march)
dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  flutter_chat_ui: ^1.6.10
  uuid: ^4.5.1
  flutter_riverpod: ^2.6.1  # Latest stable version
  web_socket_channel: ^3.0.2  # Latest stable version
  pedometer: ^4.0.2
  fl_chart: ^0.63.0
  permission_handler: ^11.4.0
  flutter_gemini: ^3.0.0
  google_generative_ai: ^0.2.0





dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


  assets:
    - assets/logo.png
    - assets/walking girl.gif

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
